// File generated by Antigravity but manually maintained.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDykgZaQpswUXtdAF_cgqlnPaGlCe_T9iM',
    appId: '1:215166996224:web:7b12ef62f4c67d72e32de5',
    messagingSenderId: '215166996224',
    projectId: 'pplan-52a07',
    authDomain: 'pplan-52a07.firebaseapp.com',
    storageBucket: 'pplan-52a07.firebasestorage.app',
    measurementId: 'G-XNR27NNFGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0q2KQApRaxH_0hvpbetPzHLDOuBHqXuk',
    appId: '1:215166996224:android:b99bc348be16cbb7e32de5',
    messagingSenderId: '215166996224',
    projectId: 'pplan-52a07',
    storageBucket: 'pplan-52a07.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0ixUIUdHXtel76J7o2mD3Uce7FRTrwQ',
    appId: '1:215166996224:ios:6878864c16daea93e32de5',
    messagingSenderId: '215166996224',
    projectId: 'pplan-52a07',
    storageBucket: 'pplan-52a07.firebasestorage.app',
    iosClientId: '215166996224-q0gjl22cni7eiprfm1qv8l7e3e0g1nus.apps.googleusercontent.com',
    iosBundleId: 'com.substring.pplan.mobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0ixUIUdHXtel76J7o2mD3Uce7FRTrwQ',
    appId: '1:215166996224:ios:6878864c16daea93e32de5',
    messagingSenderId: '215166996224',
    projectId: 'pplan-52a07',
    storageBucket: 'pplan-52a07.firebasestorage.app',
    iosClientId: '215166996224-q0gjl22cni7eiprfm1qv8l7e3e0g1nus.apps.googleusercontent.com',
    iosBundleId: 'com.substring.pplan.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNoaIfNhxqykE9QPoNZHVcFhq8nrxq-c',
    appId: '1:215166996224:web:451fa4b2ac21761fe32de5',
    messagingSenderId: '215166996224',
    projectId: 'pplan-52a07',
    authDomain: 'pplan-52a07.firebaseapp.com',
    storageBucket: 'pplan-52a07.firebasestorage.app',
    measurementId: 'G-QP0SRTSZ29',
  );

}